hooks:
  update_modules:
    post:
      - babel src -d dist
  gh_pages:
    pre:
      - echo "we'd like to use documentationjs!!"

config:
  git_user_name: CircleCI
  git_user_email: circleci@cureapp.jp
  npm_update_depth: 5
  version_prefix: v
  create_branch: false
  npm_shrinkwrap: false
  create_gh_pages: false
  gh_pages_dir: null
circle: {}
