hooks:
  update_modules:
    pre:
      - npm run babel

config:
  git_user_name: CircleCI
  git_user_email: circleci@example.com
  npm_update_depth: 5
  version_prefix: v
  create_branch: false
  npm_shrinkwrap: true
  create_gh_pages: false
  gh_pages_dir: null
circle:
  machine:
    node:
      version: 6.2.0
