env:
  node: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
installedESLint: true
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - flowtype
  - flow-vars
rules:
  comma-dangle: off
  no-unused-vars: warn
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  prefer-const: warn

  flowtype/require-return-type: 0

  flowtype/space-after-type-colon:
    - 1
    - always
  flowtype/space-before-type-colon:
    - 1
    - never
  flowtype/type-id-match:
    - 1
    - "^([A-Z][a-z0-9]+)+Type$"

  flow-vars/define-flow-type: 1
  flow-vars/use-flow-type: 1

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: false
