env:
  commonjs: true
  es6: true
extends: 'eslint:recommended'
installedESLint: true
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - flowtype
rules:
  no-unused-vars: warn
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never

  flowtype/require-return-type:
    - 1
    - always
    - { annotateUndefined: never }

  flowtype/space-after-type-colon:
    - 1
    - always
  flowtype/space-before-type-colon:
    - 1
    - never
  flowtype/type-id-match:
    - 1
    - "^([A-Z][a-z0-9]+)+Type$"

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: false
